### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by matteyeux**
Hey, 
here is a PR to build kairos on Linux distros (tested on Ubuntu 19.10).
It includes Apple's mach and mach-o headers (should be ok in term of licensing ?).

Also I changed typedef in patchfinder64.h `unsigned long long`  -> `uint64_t ` because of conflicting types.

Also tested on MacOS and it does not break anything :)

### CODE REVIEW

**Comment by dayt0n** [comment]
The licensing stuff is a bit shaky for me, but really, the mach/* and mach-o/* things are not really necessary for this particular project, they just happen to be part of the default configuration of patchfinder64. 

What might be easier is moving the `#include <mach-o/loader.h>` down to right before `init_kernel()` in patchfinder64.c and adding something like `#ifdef KERNMODE` right before the inclusion of the loader.h and `init_kernel()`. Then, add the `#endif` right after the `term_kernel()` function.

But the typedef change of `addr_t` is useful.

**Comment by matteyeux** [comment]
Got it !
I removed Apple headers and added an `ifdef` for kernel stuff. I didn't touch the Makefile though but can push something like this : 
```Makefile
KMODE ?=
ifeq ($(KERNMODE), 1)
    KMODE = -DKERNMODE
endif

all:
    gcc main.c patchfinder64.c newpatch.c decoders.c instructions.c $(KMODE) -Iinclude -o kairos
clean:
    rm kairos
```

Here is the result
```bash
λ ~/kairos(master*) » make -n
gcc main.c patchfinder64.c newpatch.c decoders.c instructions.c  -Iinclude -o kairos
λ ~/kairos(master*) » make -n KERNMODE=1
gcc main.c patchfinder64.c newpatch.c decoders.c instructions.c -DKERNMODE -Iinclude -o kairos
```

**Comment by matteyeux** [comment]
Okay so you merged before I publish my comment ^^

**Comment by dayt0n** [comment]
The KERNMODE def was just to get those issues out of the way without damaging the integrity of patchfinder64.c too much. So I am not sure if it would be necessary for future revisions to include the option to build with it. The current Makefile builds on both macOS and Linux currently. 

The Linux support works great on my end. Thanks!

**Pull request merged**
